#!/usr/bin/env sh
WORKSPACES=4

workspaces() {
  WORKSPACE_CLIENTS=$(hyprctl clients -j | jq 'group_by(.workspace.id) | map ({key: (.[0].workspace.id | tostring), value: [.[] | .title]}) | from_entries')
  seq 1 $WORKSPACES | jq --argjson windows "${WORKSPACE_CLIENTS}" --slurp -Mc 'map(tostring) | map({id: . | tonumber, windows: ($windows[.]//[]) | join("\n")})'
}

echo "{\"workspaces\": $(workspaces), \"active\": 1}"

# Lees continu de staat van de werkbladen uit de Hyprland-socket.
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  id=$(echo "$line" | awk -F '^(create)?workspacev2>>' '{print $2}' | awk -F ',' '{print $1}')

  if [ "$id" != "" ]; then
    eww update workspaces="{\"workspaces\": $(workspaces), \"active\": $id}"
  fi
done
